name: setup-dev-env
description: "Setup development environment"

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.7"
  rust-toolchain:
    description: Rust toolchain to install
    required: false
    default: stable

runs:
  using: composite

  steps:
    - name: Setup mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        use-mamba: true
        activate-environment: decocoder-dev

    - name: Set cache date
      id: cache-key
      shell: bash
      run: |
        DATE=$(date +'%Y%m%d')
        echo $DATE
        echo "DATE=$DATE" >> $GITHUB_OUTPUT

    - name: Restore conda environment
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.CONDA }}/envs
        key: ${{ runner.os }}--${{ runner.arch }}--${{ inputs.python-version }}--${{ inputs.rust-toolchain }}--${{steps.cache-key.outputs.date }}--${{ hashFiles(environment.yml, pyproject.toml, Cargo.toml) }}
        restore-keys: |
          ${{ runner.os }}--${{ runner.arch }}--${{ inputs.python-version }}--${{ inputs.rust-toolchain }}

    - name: Update conda environment
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sed 's/\python=[0-9.]\+/python=${{ inputs.python-version }}/g'
        mamba env update -n decocoder-dev -f environment.yml

    - name: Update Rust toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: rustup toolchain install ${{ inputs.rust-toolchain }}
