name: setup-dev-env
description: "Setup development environment"

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.7"
  rust-toolchain:
    description: Rust toolchain to install
    required: false
    default: stable

runs:
  using: composite

  steps:
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        default: true

    - name: Setup mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        use-mamba: true
        activate-environment: decocoder-dev

    - name: Set cache date
      id: cache-key
      shell: bash
      run: |
        DATE=$(date +'%Y%m%d')
        echo $DATE
        echo "DATE=$DATE" >> $GITHUB_OUTPUT

    - name: Restore conda environment
      uses: actions/cache@v3
      with:
        path: ${{ env.CONDA }}/envs
        key: ${{ runner.os }}--${{ runner.arch }}--${{ inputs.python-version }}--${{steps.cache-key.outputs.date }}--${{ hashFiles('environment.yml', 'pyproject.toml', 'Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}--${{ runner.arch }}--${{ inputs.python-version }}

    - name: Update conda environment if necessary
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        ls -la || true
        sed -i'' 's/python=[0-9.]\+/python=${{ inputs.python-version }}/g' environment.yml
        sed -i'' 's/- rust=[0-9.]\+//g' environment.yml
        mamba env update -n decocoder-dev -f environment.yml
