name: setup-dev-env
description: "Setup development environment"

runs:
  using: composite

  steps:
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        environment-file: environment.yaml
        activate-environment: decocoder-dev
