on:
  branches:
    - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        rust-toolchain: ["stable"]

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Debug
        run: echo ${{ matrix.os}} ${{ matrix.python-version}}
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Setup development environment
#        uses: ./.github/actions/setup-dev-env
#        with:
#          python-version: ${{ matrix.python-version }}
#          rust-toolchain: ${{ matrix.python-version }}
#
#      - name: Build wheel
#        run: maturin build --all-features

