on:
  pull_request:

jobs:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env

      - name: Check Python code format
        run: ufmt check src/python

      - name: Check Rust code format
        run: cargo fmt --check
